<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121103002848 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
			// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("CREATE TABLE famelo_demo_admin_domain_model_widgets_addresses_join (admin_widgets VARCHAR(40) NOT NULL, admin_address VARCHAR(40) NOT NULL, INDEX IDX_B9D82C5C59646648 (admin_widgets), INDEX IDX_B9D82C5CC972ED08 (admin_address), PRIMARY KEY(admin_widgets, admin_address)) ENGINE = InnoDB");
		$this->addSql("ALTER TABLE famelo_demo_admin_domain_model_widgets_addresses_join ADD CONSTRAINT FK_B9D82C5C59646648 FOREIGN KEY (admin_widgets) REFERENCES famelo_demo_admin_domain_model_widgets (persistence_object_identifier)");
		$this->addSql("ALTER TABLE famelo_demo_admin_domain_model_widgets_addresses_join ADD CONSTRAINT FK_B9D82C5CC972ED08 FOREIGN KEY (admin_address) REFERENCES famelo_demo_admin_domain_model_address (persistence_object_identifier)");
		$this->addSql("DROP TABLE famelo_demo_admin_domain_model__6ea7a_addressesmultiselect_join");
		$this->addSql("DROP TABLE famelo_demo_admin_domain_model_widgets_addressescheckboxes_join");
		$this->addSql("ALTER TABLE famelo_demo_admin_domain_model_widgets DROP FOREIGN KEY FK_B880E5C0C02FBBFF");
		$this->addSql("DROP INDEX IDX_B880E5C0C02FBBFF ON famelo_demo_admin_domain_model_widgets");
		$this->addSql("ALTER TABLE famelo_demo_admin_domain_model_widgets DROP addressradio");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
			// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("CREATE TABLE famelo_demo_admin_domain_model__6ea7a_addressesmultiselect_join (admin_widgets VARCHAR(40) NOT NULL, admin_address VARCHAR(40) NOT NULL, INDEX IDX_7B2903A259646648 (admin_widgets), INDEX IDX_7B2903A2C972ED08 (admin_address), PRIMARY KEY(admin_widgets, admin_address)) ENGINE = InnoDB");
		$this->addSql("CREATE TABLE famelo_demo_admin_domain_model_widgets_addressescheckboxes_join (admin_widgets VARCHAR(40) NOT NULL, admin_address VARCHAR(40) NOT NULL, INDEX IDX_4352A5A159646648 (admin_widgets), INDEX IDX_4352A5A1C972ED08 (admin_address), PRIMARY KEY(admin_widgets, admin_address)) ENGINE = InnoDB");
		$this->addSql("ALTER TABLE famelo_demo_admin_domain_model__6ea7a_addressesmultiselect_join ADD CONSTRAINT FK_7B2903A259646648 FOREIGN KEY (admin_widgets) REFERENCES famelo_demo_admin_domain_model_widgets (persistence_object_identifier)");
		$this->addSql("ALTER TABLE famelo_demo_admin_domain_model__6ea7a_addressesmultiselect_join ADD CONSTRAINT FK_7B2903A2C972ED08 FOREIGN KEY (admin_address) REFERENCES famelo_demo_admin_domain_model_address (persistence_object_identifier)");
		$this->addSql("ALTER TABLE famelo_demo_admin_domain_model_widgets_addressescheckboxes_join ADD CONSTRAINT FK_4352A5A159646648 FOREIGN KEY (admin_widgets) REFERENCES famelo_demo_admin_domain_model_widgets (persistence_object_identifier)");
		$this->addSql("ALTER TABLE famelo_demo_admin_domain_model_widgets_addressescheckboxes_join ADD CONSTRAINT FK_4352A5A1C972ED08 FOREIGN KEY (admin_address) REFERENCES famelo_demo_admin_domain_model_address (persistence_object_identifier)");
		$this->addSql("DROP TABLE famelo_demo_admin_domain_model_widgets_addresses_join");
		$this->addSql("ALTER TABLE famelo_demo_admin_domain_model_widgets ADD addressradio VARCHAR(40) DEFAULT NULL");
		$this->addSql("ALTER TABLE famelo_demo_admin_domain_model_widgets ADD CONSTRAINT FK_B880E5C0C02FBBFF FOREIGN KEY (addressradio) REFERENCES famelo_demo_admin_domain_model_address (persistence_object_identifier)");
		$this->addSql("CREATE INDEX IDX_B880E5C0C02FBBFF ON famelo_demo_admin_domain_model_widgets (addressradio)");
	}
}

?>