<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20131013235556 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
			// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("CREATE TABLE famelo_demo_admin_domain_model_widgets_addressesstacked_join (admin_widgets VARCHAR(40) NOT NULL, admin_address VARCHAR(40) NOT NULL, INDEX IDX_BB9105A59646648 (admin_widgets), INDEX IDX_BB9105AC972ED08 (admin_address), PRIMARY KEY(admin_widgets, admin_address))");
		$this->addSql("CREATE TABLE famelo_demo_admin_domain_model_widgets_addressestabular_join (admin_widgets VARCHAR(40) NOT NULL, admin_address VARCHAR(40) NOT NULL, INDEX IDX_BF68DD2859646648 (admin_widgets), INDEX IDX_BF68DD28C972ED08 (admin_address), PRIMARY KEY(admin_widgets, admin_address))");
		$this->addSql("CREATE TABLE famelo_demo_admin_domain_model_widgets_addressesseamless_join (admin_widgets VARCHAR(40) NOT NULL, admin_address VARCHAR(40) NOT NULL, INDEX IDX_D96C147D59646648 (admin_widgets), INDEX IDX_D96C147DC972ED08 (admin_address), PRIMARY KEY(admin_widgets, admin_address))");
		$this->addSql("ALTER TABLE famelo_demo_admin_domain_model_widgets_addressesstacked_join ADD CONSTRAINT FK_BB9105A59646648 FOREIGN KEY (admin_widgets) REFERENCES famelo_demo_admin_domain_model_widgets (persistence_object_identifier)");
		$this->addSql("ALTER TABLE famelo_demo_admin_domain_model_widgets_addressesstacked_join ADD CONSTRAINT FK_BB9105AC972ED08 FOREIGN KEY (admin_address) REFERENCES famelo_demo_admin_domain_model_address (persistence_object_identifier)");
		$this->addSql("ALTER TABLE famelo_demo_admin_domain_model_widgets_addressestabular_join ADD CONSTRAINT FK_BF68DD2859646648 FOREIGN KEY (admin_widgets) REFERENCES famelo_demo_admin_domain_model_widgets (persistence_object_identifier)");
		$this->addSql("ALTER TABLE famelo_demo_admin_domain_model_widgets_addressestabular_join ADD CONSTRAINT FK_BF68DD28C972ED08 FOREIGN KEY (admin_address) REFERENCES famelo_demo_admin_domain_model_address (persistence_object_identifier)");
		$this->addSql("ALTER TABLE famelo_demo_admin_domain_model_widgets_addressesseamless_join ADD CONSTRAINT FK_D96C147D59646648 FOREIGN KEY (admin_widgets) REFERENCES famelo_demo_admin_domain_model_widgets (persistence_object_identifier)");
		$this->addSql("ALTER TABLE famelo_demo_admin_domain_model_widgets_addressesseamless_join ADD CONSTRAINT FK_D96C147DC972ED08 FOREIGN KEY (admin_address) REFERENCES famelo_demo_admin_domain_model_address (persistence_object_identifier)");
		$this->addSql("ALTER TABLE famelo_demo_admin_domain_model_widgets ADD addressstacked VARCHAR(40) DEFAULT NULL, ADD addresstabular VARCHAR(40) DEFAULT NULL, ADD addressseamless VARCHAR(40) DEFAULT NULL");
		$this->addSql("ALTER TABLE famelo_demo_admin_domain_model_widgets ADD CONSTRAINT FK_B880E5C089232051 FOREIGN KEY (addressstacked) REFERENCES famelo_demo_admin_domain_model_address (persistence_object_identifier)");
		$this->addSql("ALTER TABLE famelo_demo_admin_domain_model_widgets ADD CONSTRAINT FK_B880E5C0B8BA99B4 FOREIGN KEY (addresstabular) REFERENCES famelo_demo_admin_domain_model_address (persistence_object_identifier)");
		$this->addSql("ALTER TABLE famelo_demo_admin_domain_model_widgets ADD CONSTRAINT FK_B880E5C0E126187D FOREIGN KEY (addressseamless) REFERENCES famelo_demo_admin_domain_model_address (persistence_object_identifier)");
		$this->addSql("CREATE INDEX IDX_B880E5C089232051 ON famelo_demo_admin_domain_model_widgets (addressstacked)");
		$this->addSql("CREATE INDEX IDX_B880E5C0B8BA99B4 ON famelo_demo_admin_domain_model_widgets (addresstabular)");
		$this->addSql("CREATE INDEX IDX_B880E5C0E126187D ON famelo_demo_admin_domain_model_widgets (addressseamless)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
			// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("DROP TABLE famelo_demo_admin_domain_model_widgets_addressesstacked_join");
		$this->addSql("DROP TABLE famelo_demo_admin_domain_model_widgets_addressestabular_join");
		$this->addSql("DROP TABLE famelo_demo_admin_domain_model_widgets_addressesseamless_join");
		$this->addSql("ALTER TABLE famelo_demo_admin_domain_model_widgets DROP FOREIGN KEY FK_B880E5C089232051");
		$this->addSql("ALTER TABLE famelo_demo_admin_domain_model_widgets DROP FOREIGN KEY FK_B880E5C0B8BA99B4");
		$this->addSql("ALTER TABLE famelo_demo_admin_domain_model_widgets DROP FOREIGN KEY FK_B880E5C0E126187D");
		$this->addSql("DROP INDEX IDX_B880E5C089232051 ON famelo_demo_admin_domain_model_widgets");
		$this->addSql("DROP INDEX IDX_B880E5C0B8BA99B4 ON famelo_demo_admin_domain_model_widgets");
		$this->addSql("DROP INDEX IDX_B880E5C0E126187D ON famelo_demo_admin_domain_model_widgets");
		$this->addSql("ALTER TABLE famelo_demo_admin_domain_model_widgets DROP addressstacked, DROP addresstabular, DROP addressseamless");
	}
}

?>