<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121004182655 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
			// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("CREATE TABLE famelo_demo_admin_domain_model_inline (persistence_object_identifier VARCHAR(40) NOT NULL, addressstacked VARCHAR(40) DEFAULT NULL, addresstabular VARCHAR(40) DEFAULT NULL, INDEX IDX_FFB8FC4589232051 (addressstacked), INDEX IDX_FFB8FC45B8BA99B4 (addresstabular), PRIMARY KEY(persistence_object_identifier)) ENGINE = InnoDB");
		$this->addSql("CREATE TABLE famelo_demo_admin_domain_model_inline_addressesstacked_join (admin_inline VARCHAR(40) NOT NULL, admin_address VARCHAR(40) NOT NULL, INDEX IDX_9EC674AE15A36C0E (admin_inline), INDEX IDX_9EC674AEC972ED08 (admin_address), PRIMARY KEY(admin_inline, admin_address)) ENGINE = InnoDB");
		$this->addSql("CREATE TABLE famelo_demo_admin_domain_model_inline_addressestabular_join (admin_inline VARCHAR(40) NOT NULL, admin_address VARCHAR(40) NOT NULL, INDEX IDX_2A17B9DC15A36C0E (admin_inline), INDEX IDX_2A17B9DCC972ED08 (admin_address), PRIMARY KEY(admin_inline, admin_address)) ENGINE = InnoDB");
		$this->addSql("ALTER TABLE famelo_demo_admin_domain_model_inline ADD CONSTRAINT FK_FFB8FC4589232051 FOREIGN KEY (addressstacked) REFERENCES famelo_demo_admin_domain_model_address (persistence_object_identifier)");
		$this->addSql("ALTER TABLE famelo_demo_admin_domain_model_inline ADD CONSTRAINT FK_FFB8FC45B8BA99B4 FOREIGN KEY (addresstabular) REFERENCES famelo_demo_admin_domain_model_address (persistence_object_identifier)");
		$this->addSql("ALTER TABLE famelo_demo_admin_domain_model_inline_addressesstacked_join ADD CONSTRAINT FK_9EC674AE15A36C0E FOREIGN KEY (admin_inline) REFERENCES famelo_demo_admin_domain_model_inline (persistence_object_identifier)");
		$this->addSql("ALTER TABLE famelo_demo_admin_domain_model_inline_addressesstacked_join ADD CONSTRAINT FK_9EC674AEC972ED08 FOREIGN KEY (admin_address) REFERENCES famelo_demo_admin_domain_model_address (persistence_object_identifier)");
		$this->addSql("ALTER TABLE famelo_demo_admin_domain_model_inline_addressestabular_join ADD CONSTRAINT FK_2A17B9DC15A36C0E FOREIGN KEY (admin_inline) REFERENCES famelo_demo_admin_domain_model_inline (persistence_object_identifier)");
		$this->addSql("ALTER TABLE famelo_demo_admin_domain_model_inline_addressestabular_join ADD CONSTRAINT FK_2A17B9DCC972ED08 FOREIGN KEY (admin_address) REFERENCES famelo_demo_admin_domain_model_address (persistence_object_identifier)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
			// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE famelo_demo_admin_domain_model_inline_addressesstacked_join DROP FOREIGN KEY FK_9EC674AE15A36C0E");
		$this->addSql("ALTER TABLE famelo_demo_admin_domain_model_inline_addressestabular_join DROP FOREIGN KEY FK_2A17B9DC15A36C0E");
		$this->addSql("DROP TABLE famelo_demo_admin_domain_model_inline");
		$this->addSql("DROP TABLE famelo_demo_admin_domain_model_inline_addressesstacked_join");
		$this->addSql("DROP TABLE famelo_demo_admin_domain_model_inline_addressestabular_join");
	}
}

?>