<?php
namespace TYPO3\FLOW3\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120517205242 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
			// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("CREATE TABLE demo_contentmanagement_domain_model_inline (flow3_persistence_identifier VARCHAR(40) NOT NULL, addressstacked VARCHAR(40) DEFAULT NULL, addresstabular VARCHAR(40) DEFAULT NULL, INDEX IDX_35BACA5289232051 (addressstacked), INDEX IDX_35BACA52B8BA99B4 (addresstabular), PRIMARY KEY(flow3_persistence_identifier)) ENGINE = InnoDB");
		$this->addSql("CREATE TABLE demo_contentmanagement_domain_model_1ed63_addressesstacked_join (contentmanagement_inline VARCHAR(40) NOT NULL, contentmanagement_address VARCHAR(40) NOT NULL, INDEX IDX_F8FD73416F8F5D7B (contentmanagement_inline), INDEX IDX_F8FD7341E967448A (contentmanagement_address), PRIMARY KEY(contentmanagement_inline, contentmanagement_address)) ENGINE = InnoDB");
		$this->addSql("CREATE TABLE demo_contentmanagement_domain_model_1ed63_addressestabular_join (contentmanagement_inline VARCHAR(40) NOT NULL, contentmanagement_address VARCHAR(40) NOT NULL, INDEX IDX_4C2CBE336F8F5D7B (contentmanagement_inline), INDEX IDX_4C2CBE33E967448A (contentmanagement_address), PRIMARY KEY(contentmanagement_inline, contentmanagement_address)) ENGINE = InnoDB");
		$this->addSql("ALTER TABLE demo_contentmanagement_domain_model_inline ADD CONSTRAINT FK_35BACA5289232051 FOREIGN KEY (addressstacked) REFERENCES demo_contentmanagement_domain_model_address (flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE demo_contentmanagement_domain_model_inline ADD CONSTRAINT FK_35BACA52B8BA99B4 FOREIGN KEY (addresstabular) REFERENCES demo_contentmanagement_domain_model_address (flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE demo_contentmanagement_domain_model_1ed63_addressesstacked_join ADD CONSTRAINT FK_F8FD73416F8F5D7B FOREIGN KEY (contentmanagement_inline) REFERENCES demo_contentmanagement_domain_model_inline (flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE demo_contentmanagement_domain_model_1ed63_addressesstacked_join ADD CONSTRAINT FK_F8FD7341E967448A FOREIGN KEY (contentmanagement_address) REFERENCES demo_contentmanagement_domain_model_address (flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE demo_contentmanagement_domain_model_1ed63_addressestabular_join ADD CONSTRAINT FK_4C2CBE336F8F5D7B FOREIGN KEY (contentmanagement_inline) REFERENCES demo_contentmanagement_domain_model_inline (flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE demo_contentmanagement_domain_model_1ed63_addressestabular_join ADD CONSTRAINT FK_4C2CBE33E967448A FOREIGN KEY (contentmanagement_address) REFERENCES demo_contentmanagement_domain_model_address (flow3_persistence_identifier)");
		$this->addSql("DROP TABLE demo_contentmanagement_domain_model__7e861_addresseschosen_join");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
			// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE demo_contentmanagement_domain_model_1ed63_addressesstacked_join DROP FOREIGN KEY FK_F8FD73416F8F5D7B");
		$this->addSql("ALTER TABLE demo_contentmanagement_domain_model_1ed63_addressestabular_join DROP FOREIGN KEY FK_4C2CBE336F8F5D7B");
		$this->addSql("CREATE TABLE demo_contentmanagement_domain_model__7e861_addresseschosen_join (contentmanagement_widgets VARCHAR(40) NOT NULL, contentmanagement_address VARCHAR(40) NOT NULL, INDEX IDX_A921BD5D7971CFCA (contentmanagement_widgets), INDEX IDX_A921BD5DE967448A (contentmanagement_address), PRIMARY KEY(contentmanagement_widgets, contentmanagement_address)) ENGINE = InnoDB");
		$this->addSql("ALTER TABLE demo_contentmanagement_domain_model__7e861_addresseschosen_join ADD CONSTRAINT FK_A921BD5D7971CFCA FOREIGN KEY (contentmanagement_widgets) REFERENCES demo_contentmanagement_domain_model_widgets (flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE demo_contentmanagement_domain_model__7e861_addresseschosen_join ADD CONSTRAINT FK_A921BD5DE967448A FOREIGN KEY (contentmanagement_address) REFERENCES demo_contentmanagement_domain_model_address (flow3_persistence_identifier)");
		$this->addSql("DROP TABLE demo_contentmanagement_domain_model_inline");
		$this->addSql("DROP TABLE demo_contentmanagement_domain_model_1ed63_addressesstacked_join");
		$this->addSql("DROP TABLE demo_contentmanagement_domain_model_1ed63_addressestabular_join");
		$this->addSql("DROP INDEX flow3_identity_demo_contentmanagement_domain_model_widgets ON demo_contentmanagement_domain_model_widgets");
	}
}

?>