<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121107010932 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
			// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("CREATE TABLE famelo_demo_admin_domain_model_validation (persistence_object_identifier VARCHAR(40) NOT NULL, required VARCHAR(255) NOT NULL, string VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, stringlength VARCHAR(255) NOT NULL, PRIMARY KEY(persistence_object_identifier)) ENGINE = InnoDB");
		$this->addSql("DROP TABLE brain_domain_model_action");
		$this->addSql("DROP TABLE brain_domain_model_action_comments_join");
		$this->addSql("DROP TABLE brain_domain_model_action_contexts_join");
		$this->addSql("DROP TABLE brain_domain_model_comment");
		$this->addSql("DROP TABLE brain_domain_model_context");
		$this->addSql("DROP TABLE brain_domain_model_information");
		$this->addSql("DROP TABLE brain_domain_model_information_contexts_join");
		$this->addSql("DROP TABLE brain_domain_model_timespan");
		$this->addSql("DROP TABLE brain_domain_model_user");
		$this->addSql("DROP TABLE famelo_adu_domain_model_answer");
		$this->addSql("DROP TABLE famelo_adu_domain_model_category");
		$this->addSql("DROP TABLE famelo_adu_domain_model_contact");
		$this->addSql("DROP TABLE famelo_adu_domain_model_group");
		$this->addSql("DROP TABLE famelo_adu_domain_model_question");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
			// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("CREATE TABLE brain_domain_model_action (persistence_object_identifier VARCHAR(40) NOT NULL, assignee VARCHAR(40) DEFAULT NULL, owner VARCHAR(40) DEFAULT NULL, burning TINYINT(1) NOT NULL, completed TINYINT(1) NOT NULL, creationdate DATETIME NOT NULL, description VARCHAR(255) NOT NULL, skippedtill DATETIME NOT NULL, title VARCHAR(255) NOT NULL, INDEX IDX_427D4ED67C9DFC0C (assignee), INDEX IDX_427D4ED6CF60E67C (owner), PRIMARY KEY(persistence_object_identifier)) ENGINE = InnoDB");
		$this->addSql("CREATE TABLE brain_domain_model_action_comments_join (brain_action VARCHAR(40) NOT NULL, brain_comment VARCHAR(40) NOT NULL, INDEX IDX_2CF067B831E5819D (brain_action), INDEX IDX_2CF067B84BD66F0 (brain_comment), PRIMARY KEY(brain_action, brain_comment)) ENGINE = InnoDB");
		$this->addSql("CREATE TABLE brain_domain_model_action_contexts_join (brain_action VARCHAR(40) NOT NULL, brain_context VARCHAR(40) NOT NULL, INDEX IDX_D47D933731E5819D (brain_action), INDEX IDX_D47D93377294B1E2 (brain_context), PRIMARY KEY(brain_action, brain_context)) ENGINE = InnoDB");
		$this->addSql("CREATE TABLE brain_domain_model_comment (persistence_object_identifier VARCHAR(40) NOT NULL, action VARCHAR(40) DEFAULT NULL, owner VARCHAR(40) DEFAULT NULL, body VARCHAR(255) NOT NULL, INDEX IDX_E5C0662747CC8C92 (action), INDEX IDX_E5C06627CF60E67C (owner), PRIMARY KEY(persistence_object_identifier)) ENGINE = InnoDB");
		$this->addSql("CREATE TABLE brain_domain_model_context (persistence_object_identifier VARCHAR(40) NOT NULL, tag VARCHAR(255) NOT NULL, title VARCHAR(255) NOT NULL, PRIMARY KEY(persistence_object_identifier)) ENGINE = InnoDB");
		$this->addSql("CREATE TABLE brain_domain_model_information (persistence_object_identifier VARCHAR(40) NOT NULL, content LONGTEXT NOT NULL, host VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, tabular LONGTEXT NOT NULL, url VARCHAR(255) NOT NULL, username VARCHAR(255) NOT NULL, variant VARCHAR(255) NOT NULL, yaml LONGTEXT NOT NULL, PRIMARY KEY(persistence_object_identifier)) ENGINE = InnoDB");
		$this->addSql("CREATE TABLE brain_domain_model_information_contexts_join (brain_information VARCHAR(40) NOT NULL, brain_context VARCHAR(40) NOT NULL, INDEX IDX_659A9EFA17BAF490 (brain_information), INDEX IDX_659A9EFA7294B1E2 (brain_context), PRIMARY KEY(brain_information, brain_context)) ENGINE = InnoDB");
		$this->addSql("CREATE TABLE brain_domain_model_timespan (persistence_object_identifier VARCHAR(40) NOT NULL, action VARCHAR(40) DEFAULT NULL, billed TINYINT(1) NOT NULL, end DATETIME NOT NULL, start DATETIME NOT NULL, INDEX IDX_AC46F03B47CC8C92 (action), PRIMARY KEY(persistence_object_identifier)) ENGINE = InnoDB");
		$this->addSql("CREATE TABLE brain_domain_model_user (persistence_object_identifier VARCHAR(40) NOT NULL, PRIMARY KEY(persistence_object_identifier)) ENGINE = InnoDB");
		$this->addSql("CREATE TABLE famelo_adu_domain_model_answer (persistence_object_identifier VARCHAR(40) NOT NULL, question VARCHAR(40) DEFAULT NULL, answer VARCHAR(255) NOT NULL, comment VARCHAR(255) NOT NULL, INDEX IDX_A0955BF3B6F7494E (question), PRIMARY KEY(persistence_object_identifier)) ENGINE = InnoDB");
		$this->addSql("CREATE TABLE famelo_adu_domain_model_category (persistence_object_identifier VARCHAR(40) NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(persistence_object_identifier)) ENGINE = InnoDB");
		$this->addSql("CREATE TABLE famelo_adu_domain_model_contact (persistence_object_identifier VARCHAR(40) NOT NULL, firstname VARCHAR(255) NOT NULL, lastname VARCHAR(255) NOT NULL, phone VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, PRIMARY KEY(persistence_object_identifier)) ENGINE = InnoDB");
		$this->addSql("CREATE TABLE famelo_adu_domain_model_group (persistence_object_identifier VARCHAR(40) NOT NULL, name VARCHAR(255) NOT NULL, `group` VARCHAR(255) NOT NULL, questions LONGTEXT NOT NULL COMMENT '(DC2Type:array)', PRIMARY KEY(persistence_object_identifier)) ENGINE = InnoDB");
		$this->addSql("CREATE TABLE famelo_adu_domain_model_question (persistence_object_identifier VARCHAR(40) NOT NULL, body VARCHAR(255) NOT NULL, weight INT NOT NULL, type VARCHAR(255) NOT NULL, PRIMARY KEY(persistence_object_identifier)) ENGINE = InnoDB");
		$this->addSql("ALTER TABLE brain_domain_model_user ADD CONSTRAINT FK_132D357247A46B0A FOREIGN KEY (persistence_object_identifier) REFERENCES typo3_party_domain_model_abstractparty (persistence_object_identifier) ON DELETE CASCADE");
		$this->addSql("DROP TABLE famelo_demo_admin_domain_model_validation");
	}
}

?>