<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121015012248 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
			// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("CREATE TABLE famelo_demo_admin_domain_model_widgets_addresses_join (admin_widgets VARCHAR(40) NOT NULL, admin_address VARCHAR(40) NOT NULL, INDEX IDX_B9D82C5C59646648 (admin_widgets), INDEX IDX_B9D82C5CC972ED08 (admin_address), PRIMARY KEY(admin_widgets, admin_address)) ENGINE = InnoDB");
		$this->addSql("CREATE TABLE famelo_demo_admin_domain_model_widgets_addresseschosen_join (admin_widgets VARCHAR(40) NOT NULL, admin_address VARCHAR(40) NOT NULL, INDEX IDX_AFB1BEC759646648 (admin_widgets), INDEX IDX_AFB1BEC7C972ED08 (admin_address), PRIMARY KEY(admin_widgets, admin_address)) ENGINE = InnoDB");
		$this->addSql("CREATE TABLE famelo_demo_admin_domain_model_inline_addressesseamless_join (admin_inline VARCHAR(40) NOT NULL, admin_address VARCHAR(40) NOT NULL, INDEX IDX_63295D1C15A36C0E (admin_inline), INDEX IDX_63295D1CC972ED08 (admin_address), PRIMARY KEY(admin_inline, admin_address)) ENGINE = InnoDB");
		$this->addSql("ALTER TABLE famelo_demo_admin_domain_model_widgets_addresses_join ADD CONSTRAINT FK_B9D82C5C59646648 FOREIGN KEY (admin_widgets) REFERENCES famelo_demo_admin_domain_model_widgets (persistence_object_identifier)");
		$this->addSql("ALTER TABLE famelo_demo_admin_domain_model_widgets_addresses_join ADD CONSTRAINT FK_B9D82C5CC972ED08 FOREIGN KEY (admin_address) REFERENCES famelo_demo_admin_domain_model_address (persistence_object_identifier)");
		$this->addSql("ALTER TABLE famelo_demo_admin_domain_model_widgets_addresseschosen_join ADD CONSTRAINT FK_AFB1BEC759646648 FOREIGN KEY (admin_widgets) REFERENCES famelo_demo_admin_domain_model_widgets (persistence_object_identifier)");
		$this->addSql("ALTER TABLE famelo_demo_admin_domain_model_widgets_addresseschosen_join ADD CONSTRAINT FK_AFB1BEC7C972ED08 FOREIGN KEY (admin_address) REFERENCES famelo_demo_admin_domain_model_address (persistence_object_identifier)");
		$this->addSql("ALTER TABLE famelo_demo_admin_domain_model_inline_addressesseamless_join ADD CONSTRAINT FK_63295D1C15A36C0E FOREIGN KEY (admin_inline) REFERENCES famelo_demo_admin_domain_model_inline (persistence_object_identifier)");
		$this->addSql("ALTER TABLE famelo_demo_admin_domain_model_inline_addressesseamless_join ADD CONSTRAINT FK_63295D1CC972ED08 FOREIGN KEY (admin_address) REFERENCES famelo_demo_admin_domain_model_address (persistence_object_identifier)");
		$this->addSql("ALTER TABLE famelo_demo_admin_domain_model_widgets ADD address VARCHAR(40) DEFAULT NULL, ADD `integer` INT DEFAULT NULL, ADD `float` DOUBLE PRECISION NOT NULL, ADD boolean TINYINT(1) NOT NULL, ADD date DATETIME NOT NULL, ADD time DATETIME NOT NULL, ADD datetime DATETIME NOT NULL, ADD textarea VARCHAR(255) NOT NULL, ADD password VARCHAR(255) NOT NULL, ADD fullrte VARCHAR(255) NOT NULL, ADD markdown VARCHAR(255) NOT NULL");
		$this->addSql("ALTER TABLE famelo_demo_admin_domain_model_widgets ADD CONSTRAINT FK_B880E5C0D4E6F81 FOREIGN KEY (address) REFERENCES famelo_demo_admin_domain_model_address (persistence_object_identifier)");
		$this->addSql("CREATE INDEX IDX_B880E5C0D4E6F81 ON famelo_demo_admin_domain_model_widgets (address)");
		$this->addSql("ALTER TABLE famelo_demo_admin_domain_model_inline ADD addressseamless VARCHAR(40) DEFAULT NULL");
		$this->addSql("ALTER TABLE famelo_demo_admin_domain_model_inline ADD CONSTRAINT FK_FFB8FC45E126187D FOREIGN KEY (addressseamless) REFERENCES famelo_demo_admin_domain_model_address (persistence_object_identifier)");
		$this->addSql("CREATE INDEX IDX_FFB8FC45E126187D ON famelo_demo_admin_domain_model_inline (addressseamless)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
			// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("DROP TABLE famelo_demo_admin_domain_model_widgets_addresses_join");
		$this->addSql("DROP TABLE famelo_demo_admin_domain_model_widgets_addresseschosen_join");
		$this->addSql("DROP TABLE famelo_demo_admin_domain_model_inline_addressesseamless_join");
		$this->addSql("ALTER TABLE famelo_demo_admin_domain_model_inline DROP FOREIGN KEY FK_FFB8FC45E126187D");
		$this->addSql("DROP INDEX IDX_FFB8FC45E126187D ON famelo_demo_admin_domain_model_inline");
		$this->addSql("ALTER TABLE famelo_demo_admin_domain_model_inline DROP addressseamless");
		$this->addSql("ALTER TABLE famelo_demo_admin_domain_model_widgets DROP FOREIGN KEY FK_B880E5C0D4E6F81");
		$this->addSql("DROP INDEX IDX_B880E5C0D4E6F81 ON famelo_demo_admin_domain_model_widgets");
		$this->addSql("ALTER TABLE famelo_demo_admin_domain_model_widgets DROP address, DROP `integer`, DROP `float`, DROP boolean, DROP date, DROP time, DROP datetime, DROP textarea, DROP password, DROP fullrte, DROP markdown");
	}
}

?>