Famelo:
  Demo:
    Admin:
      Sources:
        addresses:
          - Packages/Application/Famelo.Demo.Admin/Classes/Famelo/Demo/Admin/Domain/Model/Address.php
          - Packages/Application/Famelo.Demo.Admin/Resources/Private/TypoScripts/Schemas/Address.ts2
          - Packages/Application/Famelo.Demo.Admin/Configuration/Views.yaml

        configuration:
          - Packages/Application/Famelo.Demo.Admin/Classes/Famelo/Demo/Admin/Domain/Model/Configurations.php
          - Packages/Application/Famelo.Demo.Admin/Resources/Private/TypoScripts/Schemas/Configurations.ts2
          - Packages/Application/Famelo.Demo.Admin/Resources/Private/TypoScripts/List/CustomTable.ts2
          - Packages/Application/Famelo.Demo.Admin/Resources/Private/Elements/List/CustomTable.html
          - Packages/Application/Famelo.Demo.Admin/Configuration/Views.yaml

        inline:
          - Packages/Application/Famelo.Demo.Admin/Classes/Famelo/Demo/Admin/Domain/Model/Inline.php
          - Packages/Application/Famelo.Demo.Admin/Resources/Private/TypoScripts/Schemas/Inline.ts2
          - Packages/Application/Famelo.Demo.Admin/Configuration/Views.yaml

        widgets:
          - Packages/Application/Famelo.Demo.Admin/Classes/Famelo/Demo/Admin/Domain/Model/Widgets.php
          - Packages/Application/Famelo.Demo.Admin/Resources/Private/TypoScripts/Schemas/Widgets.ts2
          - Packages/Application/Famelo.Demo.Admin/Configuration/Views.yaml

        validation:
          - Packages/Application/Famelo.Demo.Admin/Classes/Famelo/Demo/Admin/Domain/Model/Validation.php
          - Packages/Application/Famelo.Demo.Admin/Resources/Private/TypoScripts/Schemas/Validation.ts2
          - Packages/Application/Famelo.Demo.Admin/Configuration/Views.yaml
