Famelo:
  Scaff:
    modules:
      intro:
        label: 'Intro'
        arguments:
          @controller: 'Standard'
          @package: 'Famelo.Demo.Admin'

      catalog:
        label: 'Package Catalog'
        arguments:
          @controller: 'Standard'
          @package: 'TYPO3.PackageCatalog'

      inline:
        label: 'Inline'
        arguments:
          @action: 'index'
          @controller: 'Expose'
          --exposeRuntime:
            @action: 'index'
            @controller: "SameTypeList"
            @package: "TYPO3.Expose"
            type: 'Famelo\Demo\Admin\Domain\Model\Inline'

      addresses:
        label: 'Adresses'
        arguments:
          @controller: 'Expose'
          --exposeRuntime:
              @controller: "SameTypeList"
              @action: 'index'
              @package: "TYPO3.Expose"
              type: 'Famelo\Demo\Admin\Domain\Model\Address'