Famelo:
  Scaff:
    modules:
      intro:
        label: 'Intro'
        controller: '\Demo\Admin\Controller\StandardController'

      widgets:
        label: 'Widgets'
        defaultControllerArguments:
            --scaffRuntime:
              @action: 'index'
              @controller: 'Expose'
              --exposeRuntime:
                @action: 'index'
                @controller: "SameTypeList"
                type: 'Demo\Admin\Domain\Model\Widgets'

      addresses:
        label: 'Adresses'
        defaultControllerArguments:
            --scaffRuntime:
              @controller: 'Expose'
              --exposeRuntime:
                  @controller: "SameTypeList"
                  @action: 'index'
                  type: 'Demo\Admin\Domain\Model\Address'
      users:
        label: 'Users'
        controller: '\Famelo\Scaff\Controller\ExposeController'
        defaultControllerArguments:
            --exposeRuntime:
                @controller: "sametypelist"
                @action: 'index'
                @package: 'TYPO3.Admin'
                type: 'Demo\Admin\Domain\Model\User'