Famelo:
  Scaff:
    modules:
      intro:
        label: 'Intro'
        arguments:
          @controller: 'Standard'
          @package: 'Famelo.Demo.Admin'

      typoscript:
        label: 'TypoScript'
        arguments:
          @controller: 'TypoScript'
          @package: 'Famelo.Demo.Admin'
          @typoScriptPath: 'body'

      create-form:
        label: 'New Widget'
        arguments:
          @action: 'index'
          @controller: 'Form'
          @package: 'Famelo.Demo.Admin'

      edit-form:
        label: 'Edit Widget'
        arguments:
          @action: 'edit'
          @controller: 'Form'
          @package: 'Famelo.Demo.Admin'

      widgets:
        label: 'Widgets'
        arguments:
          @action: 'index'
          @controller: 'Expose'
          --exposeRuntime:
            @action: 'index'
            @controller: "SameTypeList"
            @package: "TYPO3.Expose"
            type: 'Famelo\Demo\Admin\Domain\Model\Widgets'

      inline:
        label: 'Inline'
        arguments:
          @action: 'index'
          @controller: 'Expose'
          --exposeRuntime:
            @action: 'index'
            @controller: "SameTypeList"
            @package: "TYPO3.Expose"
            type: 'Famelo\Demo\Admin\Domain\Model\Inline'

      addresses:
        label: 'Adresses'
        arguments:
          @controller: 'Expose'
          --exposeRuntime:
              @controller: "SameTypeList"
              @action: 'index'
              @package: "TYPO3.Expose"
              type: 'Famelo\Demo\Admin\Domain\Model\Address'